### PR TITLE
send the time a user join a server

### LINKED ISSUE #4: Display the time of joining of a user

### PR DESCRIPTION
**Pull request by mohitkyadav**
sketch

Fixes #4

### CODE REVIEW

**Comment by aviaryan** [comment]
Hi @mohitkyadav,
It's not a good idea to send a PR without making an issue first. But I like this idea.
But this is too much information to show on the screen. We should only show the `HH:MM` time. 

```
user joined [08:42]
...
user2 joined [09:00]
```

Most of these chats don't have a long life that's why skipping date and everything else is better.

**Comment by mohitkyadav** [comment]
😅 issue #4 
> user joined [08:42]

sure 👍

**Comment by mohitkyadav** [comment]
done @aviaryan

**Comment by aviaryan** [comment]
@mohitkyadav Can you please provide the new screenshot as well? So as to get a preview of what it looks like now.

**Comment by mohitkyadav** [comment]
@aviaryan 
sketch

**Comment by aviaryan** [comment]
@mohitkyadav There is a small improvement that we should do here.
What if people are in different timezones? Then it will mess up the times. 

Rather, we should set the time from the server itself. When that is done, we won't require this PR, only the server's PR. https://github.com/aviaryan/chattt-backend/pull/2

What do you think?

PS - This is not the best solution but it is better. The best one would be showing users joining in everyone's local time but it might be out of scope of this PR considering how messages are showed in the client.

**Comment by mohitkyadav** [comment]
> What if people are in different timezones? Then it will mess up the times.

Yes, that is a problem.
@aviaryan Changes pushed in https://github.com/aviaryan/chattt-backend/pull/2

**Comment by aviaryan** [comment]
Thank you @mohitkyadav

**Pull request closed without merging**
